export const defaultTheme = {
    colors: {
      "base-white": "#FFFFFF",
      "base-background": "#000A0F",
      "base-card": "#0D1D25",
      "base-input": "#0D1D25",
      "base-button": "#001119",
      "base-hover": "#0D161B",
      "base-label": "#8D8686",
      "base-text": "#FFFFFF",
      "base-subtitle": "#E1E1E6",
      "base-title": "#FFFFFF",
      "base-error": "#f84747",
      "brand-purple-dark": "#065E7C",
      "brand-purple": "#1481a9",
      "brand-purple-light": "#1481a9",
      "brand-yellow-dark": "#065E7C",
      "brand-yellow": "#1481a9",
      "brand-yellow-light":"#1481a9",
      "brand-red-light":"#f84747",
    },
    textSizes: {
      "title-title-xl": "3rem",
      "title-title-l": "2rem",
      "title-title-m": "1.5rem",
      "title-title-s": "1.2rem",
      "title-title-xs": "1.125rem",
      "text-regular-l": "1.25rem",
      "text-bold-l": "1.25rem",
      "text-regular-m": "1rem",
      "text-bold-m": "1rem",
      "text-regular-s": "0.875rem",
      "text-bold-s": "0.75rem",
      "components-tag": "0.625rem",
      "components-button-g": "0.875rem",
      "components-button-s": "0.75rem",
    },
    fonts: {
      regular: "'Roboto'",
      title: "'Baloo 2'",
    },
  };